source 'https://rubygems.org'
gem 'grape'
gem 'bson', '~> 3.0'
gem 'unicorn', '4.7.0'
gem 'stripe'
gem 'rack'
gem 'rack-cors'
gem 'pg'
gem 'aws-sdk'
gem 'mini_magick'
gem 'mimemagic'
gem 'algoliasearch'
gem 'jwt'
gem 'twilio-ruby','4.12.1'
gem 'authy'
gem 'unicode_utils'
gem 'sendyr'
