source 'https://rubygems.org'
ruby '2.0.0'
gem 'grape', '0.12.0'
gem 'mongo', '~> 2.0.6'
gem 'bson', '~> 3.0'
gem 'unicorn', '4.7.0'
gem 'stripe'
gem 'mailgun-ruby'
gem 'mandrill-api'
gem 'rack'
gem 'rack-cors'
gem 'pg'
gem 'aws-sdk'
gem 'mini_magick'
